#!/bin/bash

CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o linx_amd64 main.go
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o windows_amd64.exe main.go
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o darwin_amd64 main.go
